---
title: "evaluate methods on second generation simulation: cyclic trajectory"
author: "Koen Van den Berge"
date: "6 February 2019"
output: html_document
---

```{r data}
library(slingshot)
library(RColorBrewer)
library(mgcv)
library(tradeR)
library(edgeR)
library(rafalib)
library(wesanderson)

data=readRDS("~/Dropbox/PhD/Research/singleCell/trajectoryInference/trajectoryDE/tradeRPaper/simulation/sim2_dyngen_cycle_72/72.rds")
counts <- t(data$counts)
falseGenes <- data$feature_info$gene_id[!data$feature_info$housekeeping]
nullGenes <- data$feature_info$gene_id[data$feature_info$housekeeping]

pal <- wes_palette("Zissou1", 12, type = "continuous")
truePseudotime <- data$prior_information$timecourse_continuous
g <- Hmisc::cut2(truePseudotime,g=12)

# quantile normalization
FQnorm <- function(counts){
  rk <- apply(counts,2,rank,ties.method='min')
  counts.sort <- apply(counts,2,sort)
  refdist <- apply(counts.sort,1,median)
  norm <- apply(rk,2,function(r){ refdist[r] })
  rownames(norm) <- rownames(counts)
  return(norm)
}
normCounts <- FQnorm(counts)

## dim red
pca <- prcomp(log1p(t(normCounts)), scale. = FALSE)
rd <- pca$x[,1:2]
plot(rd, pch=16, asp = 1, col=pal[g])

library(princurve)
pcc <- principal_curve(rd, smoother="periodic_lowess")
lines(x=pcc$s[order(pcc$lambda),1], y=pcc$s[order(pcc$lambda),2], col="red", lwd=2)
```

# fit smoothers on raw data

```{r}
cWeights <- rep(1,ncol(counts))
pseudoT <- matrix(pcc$lambda,nrow=ncol(counts),ncol=1)
gamList <- fitGAM(counts, pseudotime=pseudoT, cellWeights=cWeights, verbose=TRUE)
```

# Test for association of expression with the trajectory

```{r}
assocTestRes <- associationTest(gamList)
hist(assocTestRes$pvalue)
```

# tradeR on true pseudotime

```{r}
### tradeR on true pseudotime
pst <- matrix(truePseudotime, nrow=ncol(counts), ncol=1, byrow=FALSE)
gamListTrueTime <- fitGAM(counts, pseudotime=pst, cellWeights=cWeights, verbose=TRUE)
assocTestTrueRes <- associationTest(gamListTrueTime)
hist(assocTestTrueRes$pvalue)
```

# Monocle 3

```{r}
library(monocle)
fd <- data.frame(gene_short_name=rownames(counts))
fd <- new("AnnotatedDataFrame",fd)
rownames(fd) <- rownames(counts)
pd <- data.frame(cellid=colnames(counts))
pd <- new("AnnotatedDataFrame",pd)
rownames(pd) <- colnames(counts)
cds <- newCellDataSet(counts, featureData=fd, phenoData=pd)
cds <- estimateSizeFactors(cds)
cds <- estimateDispersions(cds)
cds <- preprocessCDS(cds, num_dim = 20)
cds <- reduceDimension(cds, reduction_method = 'UMAP')
cds <- partitionCells(cds)
cds <- learnGraph(cds,  RGE_method = 'SimplePPT')
pr_graph_test <- principalGraphTest(cds, k=3, cores=1)
plot_cell_trajectory(cds,color_by="cellid") # fails to discover cyclic pattern.
```

# mgcv

```{r}
gamP <- getSmootherPvalues(gamList)
```


# plot false genes

```{r}
pdf("~/Dropbox/PhD/Research/singleCell/trajectoryInference/trajectoryDE/tradeRPaper/simulation/sim2_dyngen_cycle_72/falseGenesTruePseudotime.pdf")
for(i in 1:length(falseGenes)){
   plotSmoothers(gamListTrueTime[[falseGenes[i]]])
}
dev.off()
```

# plot null genes

```{r}
pdf("~/Dropbox/PhD/Research/singleCell/trajectoryInference/trajectoryDE/tradeRPaper/simulation/sim2_dyngen_cycle_72/nullGenesTruePseudotime.pdf")
for(i in 1:length(nullGenes)){
   plotSmoothers(gamListTrueTime[[nullGenes[i]]])
}
dev.off()
```

# plot example genes

```{r}
mypar(mfrow=c(1,2))
i=1
plotSmoothers(gamListTrueTime[[falseGenes[i]]], main="false gene")
plotSmoothers(gamListTrueTime[[nullGenes[i]]], main="null gene")
```

# Performance plots

```{r}
########
# FDP-TPR
########
library(iCOBRA)
library(scales)
truth <- as.data.frame(matrix(rep(0,nrow(counts)), dimnames=list(rownames(counts),"status")))
truth[falseGenes,"status"] <- 1

### estimated pseudotime
pval <- data.frame( tradeR_slingshot_assoc=assocTestRes$pval,
                    Monocle3=pr_graph_test$pval,
                    gam=gamP[,1],
                    tradeR_slingshot_assoc_trueTime=assocTestTrueRes$pvalue,
                      row.names=rownames(counts))
cobra <- COBRAData(pval=pval, truth=truth)
saveRDS(cobra,file="~/Dropbox/PhD/Research/singleCell/trajectoryInference/trajectoryDE/tradeRPaper/simulation/sim2_dyngen_cycle_72/cobraObject.rds")
cobra <- calculate_adjp(cobra)
cobra <- calculate_performance(cobra, binary_truth="status")
cobraplot <- prepare_data_for_plot(cobra)
plot_roc(cobraplot)
plot_fdrtprcurve(cobraplot, pointsize=3/2, yaxisrange=c(0,1))
```
