---
title: "evaluate methods on second generation simulation"
author: "Koen Van den Berge"
date: "5 February 2019"
output: html_notebook
---

```{r data}
library(slingshot)
library(RColorBrewer)
library(mgcv)
library(tradeSeq)
library(edgeR)
library(rafalib)
library(wesanderson)
library(tidyverse)
library(dyno)
library(dyntoy)
library(patchwork)


# set.seed(12)
# data <- generate_dataset(
#     model = model_multifurcating(),
#     num_cells = 750,
#     num_features = 5000,
#     differentially_expressed_rate = .2
#   )

data <- readRDS("~/Dropbox/PhD/Research/singleCell/trajectoryInference/trajectoryDE/tradeSeqPaper/simulation/sim2_dyntoy_multifurcating_4/data.rds")
counts <- t(data$counts)
falseGenes <- data$tde_overall$feature_id[data$tde_overall$differentially_expressed]
nullGenes <- data$tde_overall$feature_id[!data$tde_overall$differentially_expressed]

pal <- wes_palette("Zissou1", 12, type = "continuous")
truePseudotime <- data$prior_information$timecourse_continuous[colnames(counts)]
g <- Hmisc::cut2(truePseudotime,g=12)

# quantile normalization
FQnorm <- function(counts){
  rk <- apply(counts,2,rank,ties.method='min')
  counts.sort <- apply(counts,2,sort)
  refdist <- apply(counts.sort,1,median)
  norm <- apply(rk,2,function(r){ refdist[r] })
  rownames(norm) <- rownames(counts)
  return(norm)
}
normCounts <- FQnorm(counts)

## dim red
pca <- prcomp(log1p(t(normCounts)), scale. = FALSE)
rd <- pca$x[,1:3]
plot(rd, pch=16, asp = 1)
set.seed(9)
cl <- kmeans(rd, centers = 8)$cluster
plot(rd, col = brewer.pal(9,"Set1")[cl], pch=16, asp = 1)
legend("topleft",legend=as.character(1:8),col=brewer.pal(9,"Set1")[1:8],pch=16,cex=2/3,bty='n')
 plot(rd, col = pal[g], pch=16, asp = 1)
#lineages
lin <- getLineages(rd, cl, start.clus=4, end.clus=c(1,2,8))
plot(rd, col = pal[g], pch=16, asp = 1)
lines(lin,lwd=2)
#curves
crv <- getCurves(lin)
plot(rd, col = pal[g], pch=16, asp = 1)
lines(crv, lwd=2, col="black")

# milestone ID
gid <- data$prior_information$groups_id
gid <- gid[match(colnames(counts),gid$cell_id),]
plot(rd, col = as.numeric(as.factor(gid$group_id))+1, pch=16, asp = 1)

```

# Deriving number of knots

```{r}
cWeights <- slingCurveWeights(crv)
pseudoT <- slingPseudotime(crv, na=FALSE)
icMat <- evaluateK(counts=counts,  pseudotime=pseudoT, cellWeights=cWeights,
                   nGenes=500, k=3:10)
```



# fit smoothers on raw data

```{r}
gamList <- fitGAM(counts, pseudotime=pseudoT, cellWeights=cWeights, 
                  nknots=3, verbose=FALSE)
```

# Test for differences at end point

```{r}
endRes <- diffEndTest(gamList)
hist(endRes$pvalue)
deGenesEndGam <- rownames(counts)[which(p.adjust(endRes$pvalue,"fdr")<=0.05)]
mean(falseGenes%in%deGenesEndGam) #TPR
mean(!deGenesEndGam%in%falseGenes) #FDR
```

# edgeR analysis on final clusters

```{r}
clF <- as.factor(cl)
design <- model.matrix(~clF)

library(edgeR)
d <- DGEList(counts)
d <- calcNormFactors(d)
d <- estimateDisp(d, design)
fit <- glmFit(d, design)
L <- matrix(0, nrow=ncol(fit$coefficients), ncol=3)
rownames(L) <- colnames(fit$coefficients)
colnames(L) <- c("1vs2", "2vs3", "1vs3")
L[c("clF2"),1] <- c(1)
L[c("clF8"),2] <- c(1)
L[c("clF2","clF8"),3] <- c(1,-1)
lrt <- glmLRT(fit, contrast=L) #omnibus test between end clusters (clusters 4, 6 and 7).
deGenesEdgeR <- rownames(lrt$table)[p.adjust(lrt$table$PValue,"fdr")<=0.05]
mean(falseGenes%in%deGenesEdgeR) #TPR
mean(deGenesEdgeR%in%nullGenes) #FDR
```

# compare GAM end point vs edgeR analysis

```{r}
library(rafalib)
mypar(mfrow=c(1,1))

## compare
edgeR <- p.adjust(lrt$table$PValue,"fdr")<=0.05
tradeSeq <- p.adjust(endRes$pval,"fdr")<=0.05
vennC <- cbind(edgeR,tradeSeq)
vennDiagram(vennC)
```

# Test for different expression pattern

```{r}
resPattern <- patternTest(gamList)
hist(resPattern$pval)
deGenesPattern <- rownames(counts)[which(p.adjust(resPattern$pval,"fdr")<=0.05)]
length(deGenesPattern)
mean(falseGenes%in%deGenesPattern) #TPR
mean(!deGenesPattern%in%falseGenes) #FDR
```

# Monocle BEAM analysis

```{r}
### old monocle BEAM analysis
library(monocle,lib.loc="~/Dropbox/PhD/Research/singleCell/trajectoryInference/trajectoryDE/methodsPaper/")
featureInfo <- data.frame(gene_short_name=rownames(counts))
rownames(featureInfo) <- rownames(counts)
fd <- new("AnnotatedDataFrame", featureInfo)
cds <- newCellDataSet(cellData=counts, featureData=fd, expressionFamily=negbinomial.size())
cds <- estimateSizeFactors(cds)
cds <- estimateDispersions(cds)
cds <- reduceDimension(cds)
cds <- orderCells(cds)
cds <- orderCells(cds, root_state=5)
plot_cell_trajectory(cds, color_by = "State")
# monocle does not find a branching point on 2 components! specify 4.
BEAM1 <- BEAM(cds,  cores = 1, branch_point=1)
BEAM2 <- BEAM(cds,  cores = 1, branch_point=2)
sum(BEAM1$qval<0.05) ; sum(BEAM2$qval<0.05)
library(aggregation)
pvalBeamFisher <- apply(cbind(BEAM1$pval, BEAM2$pval),1,fisher)
```

# tradeSeq downstream of Monocle 2

```{r}
phenoData(cds)$group_id <- gid$group_id
plot_cell_trajectory(cds, color_by = "group_id")
cols <- brewer.pal(9,"Set1")
plot(rd, col = cols[as.numeric(as.factor(gid$group_id))], pch=16, asp = 1) ; legend("topleft", paste0("M",1:7), col=cols,pch=16)
plot_cell_trajectory(cds, color_by = "State")
# Milestone 2 and 4 are the two branches to be compared.
ptMon <- matrix(phenoData(cds)$Pseudotime, nrow=ncol(counts), ncol=3, byrow=FALSE)
state <- phenoData(cds)$State
cellWeightsMon <- matrix(0, nrow=ncol(counts), ncol=3)
cellWeightsMon[state %in% c(2,5),] <- rep(1/3,3)
cellWeightsMon[state==4,3] <- 1 #shortest lineage
cellWeightsMon[state==3,1] <- 1 #lineage 2 as the bottom lineage
cellWeightsMon[state==1,2] <- 1 #lineage 3 as the upper lineage


plot(rd, col = cols[phenoData(cds)$State], pch=16, asp = 1) ; legend("topleft", paste0(1:5), col=cols,pch=16)

gamListMon <- fitGAM(counts[1:50,], pseudotime=ptMon, cellWeights=cellWeightsMon,
                     verbose=FALSE, nknots=3)
plotSmoothers(gamListMon[[1]])


gamListMon <- fitGAM(counts, pseudotime=ptMon, cellWeights=cellWeightsMon, 
                     verbose=FALSE, nknots=3)
resPatternMon <- patternTest(gamListMon)
resEndMon <- diffEndTest(gamListMon)
```

# GPfates

```{r}
# # export
# logCpm <- edgeR::cpm(counts, prior.count=.125, log=TRUE)
# sampleInfo <- data.frame(global_pseudotime=truePseudotime)
# rownames(sampleInfo) <- colnames(counts)
# write.table(logCpm, file="~/Dropbox/PhD/Research/singleCell/trajectoryInference/trajectoryDE/tradeSeqPaper/simulation/sim2_dyntoy_multifurcating_4/simDyntoyLogCpm.txt", row.names=TRUE, col.names=TRUE, quote=FALSE)
# write.table(sampleInfo, file="~/Dropbox/PhD/Research/singleCell/trajectoryInference/trajectoryDE/tradeSeqPaper/simulation/sim2_dyntoy_multifurcating_4/sampleInfoSimDyntoy.txt", row.names=TRUE, col.names=TRUE, quote=FALSE)
# # run GPfates python script
# system("python3 /Users/koenvandenberge/Dropbox/PhD/Research/singleCell/trajectoryInference/trajectoryDE/tradeSeqPaper/simulation/sim2_dyntoy_multifurcating_4/20190326_runGPfates_simDyntoy_multifurcating4.py")
# # import output
# GPfatesWeights <- read.table("~/Dropbox/PhD/Research/singleCell/trajectoryInference/trajectoryDE/tradeSeqPaper/simulation/sim2_dyntoy_multifurcating_4/GPfatesWeights.txt", header=FALSE)
# GPfatesBif <- read.table("~/Dropbox/PhD/Research/singleCell/trajectoryInference/trajectoryDE/tradeSeqPaper/simulation/sim2_dyntoy_multifurcating_4/GPfatesBifStats.txt", header=FALSE)
# colnames(GPfatesBif) <- c("bif_ll", "amb_ll", "shuff_bif_ll", "shuff_amb_ll", "phi0_corr", "D", "shuff_D")
```

# Performance plots

```{r}
########
# FDP-TPR
########
library(iCOBRA)
library(scales)
truth <- as.data.frame(matrix(rep(0,nrow(counts)), dimnames=list(rownames(counts),"status")))
truth[falseGenes,"status"] <- 1
cols <- hue_pal()(10)
names(cols) <- c("BEAM", "GPfates", "edgeR", "tradeSeq_slingshot_end", "tradeSeq_slingshot_pattern", "tradeSeq_GPfates_end", "tradeSeq_GPfates_pattern", "tradeSeq_Monocle2_end", "tradeSeq_Monocle2_pattern")

### estimated pseudotime
pval <- data.frame( tradeSeq_slingshot_end=endRes$pval,
                    tradeSeq_slingshot_pattern=resPattern$pval,
                    BEAM=pvalBeamFisher,
                    edgeR=lrt$table$PValue,
                    tradeSeq_Monocle2_end=resEndMon$pvalue,
                    tradeSeq_Monocle2_pattern=resPatternMon$pvalue,
                      row.names=rownames(counts))
cobra <- COBRAData(pval=pval, truth=truth)
saveRDS(cobra, file="~/Dropbox/PhD/Research/singleCell/trajectoryInference/trajectoryDE/tradeSeqPaper/simulation/sim2_dyntoy_multifurcating_4/cobra.rds")
cobra <- calculate_adjp(cobra)
cobra <- calculate_performance(cobra, binary_truth="status")
cobraplot <- prepare_data_for_plot(cobra, colorscheme=cols[match(sort(unique(cobra@roc$method)),names(cols))])
plot_roc(cobraplot)
plot_fdrtprcurve(cobraplot, pointsize=0, yaxisrange=c(0.6,1))
pEst <- plot_fdrtprcurve(cobraplot, pointsize=0, yaxisrange=c(0.6,1), xaxisrange=c(0,0.5))

```
