---
title: "evaluate methods on second generation simulation: cyclic trajectory"
author: "Koen Van den Berge"
date: "6 February 2019"
output: html_document
---

```{r data}
library(slingshot)
library(RColorBrewer)
library(mgcv)
library(tradeR)
library(edgeR)
library(rafalib)
library(wesanderson)

data=readRDS("~/Dropbox/PhD/Research/singleCell/trajectoryInference/trajectoryDE/tradeRPaper/simulation/sim2_dyngen_cycle_72/72.rds")
counts <- t(data$counts)
falseGenes <- data$feature_info$gene_id[!data$feature_info$housekeeping]
nullGenes <- data$feature_info$gene_id[data$feature_info$housekeeping]

# we will generate additional null genes by permuting cells of false genes.
set.seed(9)
permNull1 <- t(apply(counts[falseGenes,],1,sample))
dimnames(permNull1) <- list(paste0("pn",1:length(falseGenes)),colnames(counts))
permNull2 <- t(apply(counts[falseGenes,],1,sample))
dimnames(permNull2) <- list(paste0("pn",(length(falseGenes)+1):(2*length(falseGenes))),colnames(counts))
permNull3 <- t(apply(counts[falseGenes,],1,sample))
dimnames(permNull3) <- list(paste0("pn",(2*length(falseGenes)+1):(3*length(falseGenes))),colnames(counts))
counts <- rbind(counts, permNull1, permNull2, permNull3)


pal <- wes_palette("Zissou1", 12, type = "continuous")
truePseudotime <- data$prior_information$timecourse_continuous
g <- Hmisc::cut2(truePseudotime,g=12)

# quantile normalization
FQnorm <- function(counts){
  rk <- apply(counts,2,rank,ties.method='min')
  counts.sort <- apply(counts,2,sort)
  refdist <- apply(counts.sort,1,median)
  norm <- apply(rk,2,function(r){ refdist[r] })
  rownames(norm) <- rownames(counts)
  return(norm)
}
normCounts <- FQnorm(counts)

## dim red
pca <- prcomp(log1p(t(normCounts)), scale. = FALSE)
rd <- pca$x[,1:2]
plot(rd, pch=16, asp = 1, col=pal[g])

library(princurve)
pcc <- principal_curve(rd, smoother="periodic_lowess")
lines(x=pcc$s[order(pcc$lambda),1], y=pcc$s[order(pcc$lambda),2], col="red", lwd=2)
```

# fit smoothers on raw data

```{r}
cWeights <- rep(1,ncol(counts))
pseudoT <- matrix(pcc$lambda,nrow=ncol(counts),ncol=1)
gamList <- fitGAM(counts, pseudotime=pseudoT, cellWeights=cWeights, verbose=FALSE)
```

# Test for association of expression with the trajectory

```{r}
assocTestRes <- associationTest(gamList)
hist(assocTestRes$pvalue)
```

# tradeR on true pseudotime

```{r}
### tradeR on true pseudotime
pst <- matrix(truePseudotime, nrow=ncol(counts), ncol=1, byrow=FALSE)
gamListTrueTime <- fitGAM(counts, pseudotime=pst, cellWeights=cWeights, verbose=TRUE)
assocTestTrueRes <- associationTest(gamListTrueTime)
hist(assocTestTrueRes$pvalue)
```

# Monocle 3

```{r}
library(monocle)
fd <- data.frame(gene_short_name=rownames(counts))
fd <- new("AnnotatedDataFrame",fd)
rownames(fd) <- rownames(counts)
pd <- data.frame(cellid=colnames(counts))
pd <- new("AnnotatedDataFrame",pd)
rownames(pd) <- colnames(counts)
cds <- newCellDataSet(counts, featureData=fd, phenoData=pd)
cds <- estimateSizeFactors(cds)
cds <- estimateDispersions(cds)
cds <- preprocessCDS(cds, num_dim = 20)
cds <- reduceDimension(cds, reduction_method = 'UMAP')
cds <- partitionCells(cds)
cds <- learnGraph(cds,  RGE_method = 'SimplePPT')
pr_graph_test <- principalGraphTest(cds, k=3, cores=1)
plot_cell_trajectory(cds, color_by=NULL)
```

# mgcv

```{r}
hlp=getSmootherPvalues(gamList)
```

# Performance plots

```{r}
########
# FDP-TPR
########
library(iCOBRA)
library(scales)
truth <- as.data.frame(matrix(rep(0,nrow(counts)), dimnames=list(rownames(counts),"status")))
truth[falseGenes,"status"] <- 1

### estimated pseudotime
pval <- data.frame( tradeR_slingshot_assoc=assocTestRes$pval,
                    Monocle3=pr_graph_test$pval,
                    gam=hlp[,1],
                    tradeR_slingshot_assoc_trueTime=assocTestTrueRes$pvalue,
                      row.names=rownames(counts))
cobra <- COBRAData(pval=pval, truth=truth)
cobra <- calculate_adjp(cobra)
cobra <- calculate_performance(cobra, binary_truth="status")
cobraplot <- prepare_data_for_plot(cobra)
plot_roc(cobraplot)
plot_fdrtprcurve(cobraplot, pointsize=3/2, yaxisrange=c(0,1))
```

# tradeR with UMAP

```{r}
umapDims <- t(reducedDimS(cds))
plot(umapDims, pch=16, asp = 1, col=pal[g])

library(princurve)
pccUmap <- principal_curve(umapDims, smoother="periodic_lowess")
lines(x=pccUmap$s[order(pccUmap$lambda),1], y=pccUmap$s[order(pccUmap$lambda),2], col="red", lwd=2)
```

# fit smoothers on UMAP trajectory

```{r}
cWeights <- rep(1,ncol(counts))
pseudoT <- matrix(pccUmap$lambda,nrow=ncol(counts),ncol=1)
gamListUmap <- fitGAM(counts, pseudotime=pseudoT, cellWeights=cWeights, verbose=FALSE)
```

# Test for association of expression with the trajectory

```{r}
assocTestUmap <- associationTest(gamListUmap)
hist(assocTestUmap$pvalue)
```

# Performance plots

```{r}
### estimated pseudotime
pval <- data.frame( tradeR_slingshot_PCA=assocTestRes$pval,
                    Monocle3=pr_graph_test$pval,
                    #gam=hlp[,1],
                    #tradeR_slingshot_assoc_trueTime=assocTestTrueRes$pvalue,
                    tradeR_slingshot_UMAP=assocTestUmap$pvalue,
                      row.names=rownames(counts))
cobra <- COBRAData(pval=pval, truth=truth)
cobra <- calculate_adjp(cobra)
cobra <- calculate_performance(cobra, binary_truth="status")
cobraplot <- prepare_data_for_plot(cobra)
#facetted(cobraplot) <- FALSE
plot_roc(cobraplot)
perUMAP <- plot_fdrtprcurve(cobraplot, pointsize=0, yaxisrange=c(0,1), xaxisrange=c(0,0.5), stripsize=0)
perUMAP + xlab("FDP") + theme(axis.title.x = element_text(size = rel(1.5)),
                              axis.title.y = element_text(size = rel(1.5)),
                              axis.text.x=element_text(size=rel(1.2)),
                              axis.text.y=element_text(size=rel(1.2)))
```

# plot for supplementary

```{r}
library(ggplot2)

# PCA trajectory
ggPCA <- ggplot(as.data.frame(rd), aes(x=PC1, y=PC2))
ggPCA + geom_point(col="gray") + theme_bw() + geom_path(x=pcc$s[order(pcc$lambda),1], y=pcc$s[order(pcc$lambda),2])

# UMAP trajectory
umapDims <- data.frame(UMAP1=umapDims[,1], UMAP2=umapDims[,2])
ggUMAP <- ggplot(as.data.frame(umapDims), aes(x=UMAP1, y=UMAP2))
ggUMAP + geom_point(col="gray") + theme_bw() + geom_path(x=pccUmap$s[order(pccUmap$lambda),1], y=pccUmap$s[order(pccUmap$lambda),2])



library(cowplot)
prow <- plot_grid( ggPCA + geom_point(col="gray") + theme_bw() + geom_path(x=pcc$s[order(pcc$lambda),1], y=pcc$s[order(pcc$lambda),2]),
           ggUMAP + geom_point(col="gray") + theme_bw() + geom_path(x=pccUmap$s[order(pccUmap$lambda),1], y=pccUmap$s[order(pccUmap$lambda),2]),
           align = 'vh',
           labels = c("a", "b"),
           hjust = -1,
           nrow = 1,
           ncol = 2
           )
prow

plot_grid(prow,
          perUMAP + xlab("FDP") + theme(axis.title.x = element_text(size = rel(1.5)),
                                        axis.title.y = element_text(size = rel(1.5)),
                                        axis.text.x=element_text(size=rel(1.2)),
                                        axis.text.y=element_text(size=rel(1.2))),
          nrow=2, ncol=1, rel_heights=c(2/3,1), labels=c("","c"))

ggsave("~/Dropbox/PhD/Research/singleCell/trajectoryInference/trajectoryDE/tradeRPaper/simulation/sim2_dyngen_cycle_72/permutedGenes/trajectoryWithPermGenes.pdf")

```
